receivers:
    # https://github.com/open-telemetry/opentelemetry-collector/tree/main/receiver/otlpreceiver
    otlp:
        protocols:
            grpc:
                endpoint: localhost:9312
            http:
                endpoint: localhost:9313

    # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/hostmetricsreceiver
    hostmetrics:
        collection_interval: 5s
        scrapers:
            cpu: {}
            # load: {}
            # memory: {}
            # paging: {}
            # disk: {}
            # filesystem: {}
            # network: {}
            # processes: {}
            # process: {}
    
    # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/dockerstatsreceiver
    docker_stats:
        endpoint: unix:///var/run/docker.sock
        collection_interval: 5s
        timeout: 20s
        api_version: 1.24
    
    # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/prometheusreceiver
    prometheus:
        config:
            scrape_configs:
                - job_name: otel-collector
                  scrape_interval: 5s
                  static_configs:
                    - targets:
                        - 0.0.0.0:8888

    # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/filelogreceiver
    filelog:
        include:
            - /var/log/**/*.log*
            
processors:
    # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/resourceprocessor
    resource/common:
        attributes:
            - key: common-key
              action: insert
              value: common-value
    resource/metrics:
        attributes:
            - key: metric-key
              action: insert
              value: metric-value
    resource/traces:
        attributes:
            - key: trace-key
              action: insert
              value: trace-value
    resource/logs:
        attributes:
            - key: log-key
              action: insert
              value: log-value
    
    # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/resourcedetectionprocessor
    resourcedetection:
        detectors:
            - env
            - system
            - docker
        timeout: 5s
        override: false

exporters:
    # https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/loggingexporter
    logging:
        verbosity: detailed

    # https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/otlpexporter
    otlp/2:
        tls:
            insecure: true
        endpoint: localhost:9314
        headers:
            authorization: 'auth-header'
        sending_queue:
            enabled: true
            num_consumers: 100
            queue_size: 10000

extensions:
    # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/healthcheckextension
    health_check:
    # localhost:13133

service:
    extensions: [ health_check ]
    pipelines:
        metrics:
            receivers:
                - hostmetrics
                # - prometheus
            processors:
                - resourcedetection
                - resource/common
                - resource/metrics
            exporters:
                - logging
                # - otlp/2
        # logs:
        #     receivers:
        #         - otlp
        #         - fluentforward
        #         - filelog
        #     processors:
        #         - resourcedetection
        #         - resource/common
        #         - resource/traces
        #     exporters:
        #         - otlp/2
        # traces:
        #     receivers:
        #         - otlp
        #     processors:
        #         - resourcedetection
        #         - resource/common
        #         - resource/logs
        #     exporters:
        #         - otlp/2
    telemetry:
        logs:
            level: debug
        metrics:
            # default: 0.0.0.0:8888
            address: 0.0.0.0:8970